# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nll_mjd <- function(X, dt, r, lsigma, llambda, mu, lnu, length, n, ift_type) {
    .Call(`_ExactSPA_nll_mjd`, X, dt, r, lsigma, llambda, mu, lnu, length, n, ift_type)
}

nll_nchisq <- function(X, ldf, lncp, length, n, ift_type) {
    .Call(`_ExactSPA_nll_nchisq`, X, ldf, lncp, length, n, ift_type)
}

nll_nig <- function(X, lchi, lpsi, mu, gamma, length, n, ift_type) {
    .Call(`_ExactSPA_nll_nig`, X, lchi, lpsi, mu, gamma, length, n, ift_type)
}

